on: [push]

name: CI

jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build the docker image with latest tag for dockerhub
      run: |
        echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        docker-compose -f docker-compose-dockerhub.yaml build
      if: github.ref == 'refs/heads/master'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: branch Push Docker image to dockerhub registry with latest tag
      run: |
        echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        docker-compose -f docker-compose-dockerhub.yaml push
      if: github.ref == 'refs/heads/master'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
